### ISSUE TITLE
Why P(Rj) in exercise3.6 is derived from 3.106 and 3.116 instead of P(Rj) == 1 

### ISSUE THREAD

**Issue by Crrush83** [jezgillen/JaynesProbabilityTheory#2]
given that Vj  = [0,1] (3.126)
why P(Rj) can't just be 1 ?

**Comment by MaksimIM** [comment]
In the formula 3.129 our state of knowledge is C, it does not include direct information about R_j having occurred. So all probabilities there must be conditioned on C and, unless additionally specified, on nothing else. In particular P(R_j) is really P(R_j|C) and is given by 3.118 with k replaced by j.

You could try to do a calculation conditioned on R_j. For example, if you condition all probabilities in 3.129 on R_j you will have P(R_j)=1 but then also P(R_j|R_k R_j)=1, and you just end up with a tautology P(R_k|R_j)=P(R_j|R_k).
